language: objective-c

matrix:
  include:
    - osx_image: xcode12
    - osx_image: xcode11.6
    - osx_image: xcode10

os:
  - osx

sudo: false

script:
  - gcc -O0 hello.c -o hello
  - ./hello

after_success:
  - echo "Done"
